# Generated by Django 5.2.3 on 2025-06-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_appointment_message_recoveryprogress_vitalsign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='surgery_date',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='surgery_type',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
